######################################################################
# Automatically generated by qmake (2.01a) lun mar 17 15:35:42 2008
######################################################################

#TEMPLATE = app
#TARGET = 
#DEPENDPATH += .
#INCLUDEPATH += .

# Input
SOURCES         += lector.py
FORMS           += ui_lector.ui
TRANSLATIONS    =   ts/lector_it_IT.ts
